### ISSUE TITLE
Ability to "Open with" an SVG

### ISSUE THREAD

**Issue by netmute** [alexgurr/svgsplash#2]
Currently I can only open SVGs by dragging them onto the app.
When I set "SVG Splash" as default app for SVGs, the software starts but doesn't open the file.

I want to use it like any other app, and just click an SVG and have it open in SVG Splash.

**Comment by alexgurr** [comment]
Hi Simon! Good idea. I'll take a look into this.

**Comment by alexgurr** [comment]
This has been added to the latest version, 1.3.0. Please update your app in the App Store!

**Comment by alexgurr** [comment]
If you wouldn't mind showing me some love (rating wise) in the App Store, it really helps me out 🔥🔥
